// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvQdx9W9X_qdsEVYGDnZCpQfnnTAv15oc',
    appId: '1:372482326957:web:d5c43dae549d6f5d6d2124',
    messagingSenderId: '372482326957',
    projectId: 'aceup-app-123',
    authDomain: 'aceup-app-123.firebaseapp.com',
    storageBucket: 'aceup-app-123.firebasestorage.app',
    measurementId: 'G-25E7LSKEGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmuN2IJQfpzuWgO5SvsHKhY89AjV8OLWk',
    appId: '1:372482326957:android:74f7ad8255ce5fd06d2124',
    messagingSenderId: '372482326957',
    projectId: 'aceup-app-123',
    storageBucket: 'aceup-app-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdSgEa6jyw7cqyM4DI7G4lA6n5_Ce-tGE',
    appId: '1:372482326957:ios:9f35e3e0f9f398206d2124',
    messagingSenderId: '372482326957',
    projectId: 'aceup-app-123',
    storageBucket: 'aceup-app-123.firebasestorage.app',
    iosBundleId: 'com.aceup.aceupClean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdSgEa6jyw7cqyM4DI7G4lA6n5_Ce-tGE',
    appId: '1:372482326957:ios:9f35e3e0f9f398206d2124',
    messagingSenderId: '372482326957',
    projectId: 'aceup-app-123',
    storageBucket: 'aceup-app-123.firebasestorage.app',
    iosBundleId: 'com.aceup.aceupClean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvQdx9W9X_qdsEVYGDnZCpQfnnTAv15oc',
    appId: '1:372482326957:web:e36a8b4b3655f4296d2124',
    messagingSenderId: '372482326957',
    projectId: 'aceup-app-123',
    authDomain: 'aceup-app-123.firebaseapp.com',
    storageBucket: 'aceup-app-123.firebasestorage.app',
    measurementId: 'G-S6LBD069LN',
  );

}